spring.application.name=springboot-web
server.port=8081
logging.level.root=info
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_web
spring.datasource.username=diego
spring.datasource.password=diego
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true